### PR TITLE
Add an x86_64 NASM implementation

### PR DESCRIPTION
**Pull request by Sirraide**
Note: This doesn’t work on Windows because the calling convention is hard-coded.

### CODE REVIEW

**Comment by Sirraide** [comment]
This already works, but I’ve decided to refactor it a bit. Should be done soon.

**Comment by Sirraide** [comment]
Alright, refactor done. It’s a lot more organised now I’d say. :eyes:

**Comment by novusnota** [comment]
Merging in https://github.com/novusnota/monkey-deez real soon

**Comment by Sirraide** [comment]
> Merging in https://github.com/novusnota/monkey-deez real soon

Seems like you’ve already merged it. Should I close this pr here then?

**Review by vhladko — APPROVED** [review]
looks crazy, thanks for your effort, gonna merge it !

**Pull request merged**
