### PR TITLE
Add Assembly as language (NASM)

### PR DESCRIPTION
**Pull request by onehunga**

### CODE REVIEW

**Comment by Sirraide** [comment]
I already have a PR open for that just saying :eyes: 

https://github.com/ThePrimeagen/ts-rust-zig-deez/pull/59

**Comment by novusnota** [comment]
Merging in https://github.com/novusnota/monkey-deez

**Comment by vhladko** [comment]
@onehunga @iamevie I'm a little bit lost on who is the author of this PR, but anyway, you should add yourself as a CODEOWNER to language. And we've just merged https://github.com/ThePrimeagen/ts-rust-zig-deez/pull/59 by @Sirraide so you are welcome to contribute to already existed code, or if you want to keep your implementation - you still need to add yourself as a codeowner :)

**Comment by onehunga** [comment]
Hello @vhladko,

thanks for the tip, we have added both our names. We would like to work on our own implementation in parallel.

Thanks in advance :)

**Comment by vhladko** [comment]
@onehunga sorry, but could you pls resolve conflict in a CODEOWNERS ? Scala owner should be there :)

**Comment by vhladko** [comment]
@onehunga nice, here we go :)

**Comment by onehunga** [comment]
@vhladko thank you :)

**Pull request merged**
