### PR TITLE
refactor(fsharp) Remove mutations

### PR DESCRIPTION
**Pull request by kram1138**
Makes the code more "functional" F# code as opposed to a direct implementation of the interpreter book

### CODE REVIEW

**Comment by meenzen** [comment]
I like it, especially because this uses a sequence expression instead of my janky list concatenation.

**Comment by bjornkihlberg** [comment]
You could use computation expressions to implement a parser monad.

**Review by meenzen — CHANGES_REQUESTED** [review]
Would you mind rebasing this on main?

**Comment by vhladko** [comment]
@meenzen are you good with changes, can we merge it ?

**Review by meenzen — APPROVED** [review]
LGTM

**Comment by vhladko** [comment]
Nice, will merge :)

**Pull request merged**
