### PR TITLE
feat: create brainf*ck lexer

### PR DESCRIPTION
**Pull request by sno2**
It took longer than expected for me to finish this because some of the memory was unexpected in some places because of scratch cells which ended up causing issues in a few tests.

I guess we might be able to pipe this to a `parser.b` file which can read the tokens out using the binary format later. However, that will be a lot more work than this.

### CODE REVIEW

**Comment by vhladko** [comment]
Pls add yourself as a Codeowner :)

**Comment by sno2** [comment]
The codeowners don't work unless if we have write perms.

**Comment by vhladko** [comment]
I know, but it will be changed in future, right now we just need to keep track of codeowners, so pls, add yourself :)

**Comment by sno2** [comment]
ok, I pushed the CODEOWNERS change

**Comment by vhladko** [comment]
Then we can go :)

**Pull request merged**
