### PR TITLE
Add Haxe language implementation.

### PR DESCRIPTION
**Pull request by koteelok**
Language website btw - https://haxe.org/

### CODE REVIEW

**Comment by novusnota** [comment]
Merging in https://github.com/novusnota/monkey-deez

**Comment by koteelok** [comment]
> Merging in https://github.com/novusnota/monkey-deez

Project is moving to another repo?

**Comment by vhladko** [comment]
Wow, I've never heard of that language, I'll merge this and add you as CODEOWNER. Could you also take a look if Dokerfile or something else is needed to easily run it ?

**Comment by koteelok** [comment]
> Wow, I've never heard of that language, I'll merge this and add you as CODEOWNER. Could you also take a look if Dokerfile or something else is needed to easily run it ?

I will try, but Haxe have so much build targets...

**Pull request merged**
