### PR TITLE
feat(crystal): update implementation

### PR DESCRIPTION
**Pull request by devnote-dev**
Updates the lexer implementation based on the ~~OCaml~~ PHP implementation, parser stages and the REPL are still being worked on.

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
add yourself as code owner
and mark approved when ready
ping me

**Comment by devnote-dev** [comment]
Moving to [novusnota/monkey-deez](https://github.com/novusnota/monkey-deez) as per #114.

**Comment by devnote-dev** [comment]
Reopening as per novusnota/monkey-deez#7.

**Comment by vhladko** [comment]
Is it still draft ?

**Comment by devnote-dev** [comment]
It is, I will try to get it up to date with others when available.

**Comment by devnote-dev** [comment]
The updated lexer, new parser and basic interactive REPL (which I think you'll like) have been added now. Sorry for the wait, infix operators were quite a challenge... 😅

**Pull request merged**
