### PR TITLE
java: Use Map.of

### PR DESCRIPTION
**Pull request by andirady**

### CODE REVIEW

**Comment by vhladko** [comment]
@xNaCly could you take a look to this one ?

**Comment by xNaCly** [comment]
The second change is already in https://github.com/ThePrimeagen/ts-rust-zig-deez/pull/108, i dont think i can approve this one

**Comment by vhladko** [comment]
@andirady there are some conflict after latest PR to java folder, can you take a look to it ? :)

**Comment by andirady** [comment]
@vhladko I'm not used to git. I made a mistake. 😂

**Comment by vhladko** [comment]
No problem, I’ll re open PR :)

**Comment by vhladko** [comment]
Was closed by mistake

**Comment by vhladko** [comment]
Oh, looks like I can’t do that, could you create a new one, pls ?)

**Comment by andirady** [comment]
> Oh, looks like I can’t do that, could you create a new one, pls ?)

The code doesn't use Map anymore. So this PR should be closed.

**Pull request closed without merging**
