### PR TITLE
chore(php): Add composer and phpunit

### PR DESCRIPTION
**Pull request by arbezerra**
Refactored the code to use composer autoload and phpunit for tests.

### CODE REVIEW

**Comment by vhladko** [comment]
@wartab can you take a look to this one ? :)

**Comment by wartab** [comment]
This needs to be updated to reflect the current state of the code.

**Comment by vhladko** [comment]
@arbezerra can you look and make needed changes ?

**Comment by arbezerra** [comment]
@vhladko @wartab 
Done

**Comment by wartab** [comment]
Looks good to me. Not a big fan of the reformatting that consists in sometimes putting braces on their own lines, but I can get to changing that myself.

**Review by wartab — APPROVED** [review]

**Pull request merged**
