### PR TITLE
lean4 deez start

### PR DESCRIPTION
**Pull request by DerPesky**
haven't implemented a lot of stuff nor is everything correct, but just to get the lang/dir into the project to work off of later.

### CODE REVIEW

**Comment by novusnota** [comment]
Merging in https://github.com/novusnota/monkey-deez

**Comment by vhladko** [comment]
@DerPesky is it ready to be merged ? We can mark it as a draft till you finish, or if it works, we can merge it, I'll only ask you to add yourself as CODEOWNER :)

**Comment by DerPesky** [comment]
> 

Right now, it follows the rust implementation (so as long as that ones good it should work). But i do plan on adding tests/proofs later. Also, added myself to codeowners files. Think everything is good?

> @DerPesky is it ready to be merged ? We can mark it as a draft till you finish, or if it works, we can merge it, I'll only ask you to add yourself as CODEOWNER :)

Right now, it follows the rust implementation (so as long as that ones good it should work). But i do plan on adding tests/proofs later. Also, added myself to codeowners files. Think everything is good?

**Comment by vhladko** [comment]
@DerPesky sure, then pls mark PR as a draft till it’s ready, and check pls your changes to codeowners, for some reason you also add Java owner

**Pull request closed without merging**
