### PR TITLE
C# Improvements

### PR DESCRIPTION
**Pull request by leo-costa**
- Follow instructions on README to make a Makefile available at the root of the project.
- Improve performance by 30% and memory usage by 60%.
- Mimics the Rust implementation as much as possible.
- Add self to CODEOWNERS.

### CODE REVIEW

**Comment by vhladko** [comment]
@MarioGK could you take a look to this one ?
@leo-costa are these changes just improvements or brand-new implementation ? If second, you may want to create a separate folder and add yourself as CODEOWNER :)

**Comment by leo-costa** [comment]
> @MarioGK could you take a look to this one ? @leo-costa are these changes just improvements or brand-new implementation ? If second, you may want to create a separate folder and add yourself as CODEOWNER :)

I would consider this an improvement because [TomasDurica](https://github.com/TomasDurica) has a PR that is really close to what I did. This PR also has all of the README requests to run the code with and without Docker.

I added myself to the CODEOWNER here too 👍 .

**Comment by vhladko** [comment]
It’s up to you, if you feel that it’s improvement - we could wait for review from Codeowner, if it’s more like different approach, then you could go with a separate folder :)

**Comment by redducks100** [comment]
Hey @leo-costa, the implementation looks good and similar to mine (check #79). I suggest we push yours as new C# implementation with you as a Codeowner and maybe me (wink) as it seems to me @MarioGK is not that active to look over PRs. We can use this a base to push further changes to.

**Comment by leo-costa** [comment]
> It’s up to you, if you feel that it’s improvement - we could wait for review from Codeowner, if it’s more like different approach, then you could go with a separate folder :)

Done! Created a `csharp2` and added myself and @redducks100 as maintainers :) You can merge this now. Thank you!

**Comment by leo-costa** [comment]
> Hey @leo-costa, the implementation looks good and similar to mine (check #79). I suggest we push yours as new C# implementation with you as a Codeowner and maybe me (wink) as it seems to me @MarioGK is not that active to look over PRs. We can use this a base to push further changes to.

Nice! Did that. I want to run your implementation, which my initial one was really close to that 😁, against the one on this PR to see some results.

**Comment by vhladko** [comment]
Nice, then let’s go with it :)

**Comment by redducks100** [comment]
> > Hey @leo-costa, the implementation looks good and similar to mine (check #79). I suggest we push yours as new C# implementation with you as a Codeowner and maybe me (wink) as it seems to me @MarioGK is not that active to look over PRs. We can use this a base to push further changes to.
> 
> Nice! Did that. I want to bench your implementation, which my initial one was really close to that 😁, against the one on this PR to see some results.

I would love to see some results of your benchmark as I didn't have time myself to do it :D

**Comment by leo-costa** [comment]
> ld love to see some results of your benchmark as I didn't have time myself to do it :D

I'll run some both of your PR (plz don't close it yet) and on [TomasDurica](https://github.com/TomasDurica)'s code. I'll report back later today on this when my kids go to sleep :D

**Comment by MarioGK** [comment]
Hey guys, well if you want you can take over the csharp implementation, i am not having that much time to improve or contribute with the code, my first implementation was just a simple and quick way to get things done as i was planning to implement span later on.

**Pull request merged**
