### PR TITLE
added golang implementation

### PR DESCRIPTION
**Pull request by GiorgosAthanasopoulos**
Added golang implementation.
Source files: (lexer) lexer.go, (tests) go_deez_test.go
Run: ./run.sh or using docker
CLI run tests command: go test -v (-v = verbose - optional)

Small edit: Im a beginner in go, so my implementation may not be the most "go" way to do it. I did use as many useful features of go that i knew as possible, and the api is really similar to the ts version.

### CODE REVIEW

**Comment by novusnota** [comment]
Merging in https://github.com/novusnota/monkey-deez

**Review by vhladko — DISMISSED** [review]
looks good, gonna merge :)

**Comment by vhladko** [comment]
Sorry, my bad, @GiorgosAthanasopoulos can you add yourself as a codeowner ?

**Review by vhladko — APPROVED** [review]
@GiorgosAthanasopoulos never-mind, I'll add you as a codeowner by myself :)

**Comment by GiorgosAthanasopoulos** [comment]
Thnx

**Pull request merged**
