### PR TITLE
Refactor haskell lens implementation using State operators

### PR DESCRIPTION
**Pull request by ambroslins**
There are specific lens operators for the state monad. I think this implementation is a bit clearer and better shows the power of lenses.
However I would like to know what @alexjercan, @newmaidumosa and @Ofenhed think about this before I update the README.

### CODE REVIEW

**Comment by vhladko** [comment]
@alexjercan could you take a look to this ? :)

**Comment by alexjercan** [comment]
I added some comments with some fixes. Also the rest of the code looks good. Pretty interesting operators :)

**Comment by alexjercan** [comment]
can you also do `make fmt` just to use the same formatter everywhere?

**Comment by Ofenhed** [comment]
Not having used lenses much (as I think they produce confusing code) I can only agree with @alexjercan. The diff was too big (just looking on my phone it looked as if a lot was pure styling), but the operators were very interesting 😊

**Comment by ambroslins** [comment]
Sorry i forgot to run `make fmt` on the last commit. Should be fixed now.

> I added some comments with some fixes. Also the rest of the code looks good. Pretty interesting operators :)

Where did you add these comments? I can't find them.

I should be able to update the README within the next 24h.

**Comment by Ofenhed** [comment]
@alexjercan Did you remember to commit the comments? They are all stuck as pending until you send them as either plain comments, accept review, or reject review.

**Comment by alexjercan** [comment]
> Where did you add these comments? I can't find them.

Oh you are right, they were pending. No worries, it was related to the imports, it is all good now.

**Comment by vhladko** [comment]
Is it good for merge now ?

**Comment by Ofenhed** [comment]
The README references the old operators, so I would say it should be updated before it's merged. A simple explanation of how `.=` relates to the already explained `a & b .~ c` would probably be enough.

**Comment by alexjercan** [comment]
> Is it good for merge now ?

will ping you when it is ready

**Comment by ambroslins** [comment]
@alexjercan, @Ofenhed. I have updated the README. Feel free to leave suggestions.

And thank you for the feedback on the implementation.

**Comment by alexjercan** [comment]
Yeah, it looks good to me. @vhladko I think it is ok to merge it

**Pull request merged**
