### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by Spongman**
adding myself to cpp

### CODE REVIEW

**Comment by vhladko** [comment]
@nicdgonzalez are you fine with that ? :)

**Comment by nicdgonzalez** [comment]
@vhladko @Spongman

## Proposal
I propose an alternative where we move the project currently in `cpp` into a new directory called `cpp-spongman` and make Spongman the code owner for that directory.

## Rationale
At the beginning of the repo, I was originally the maintainer for the `cpp` directory. At the time of Spongman's initial pull request, there were no languages that had more than one directory. Because Spongman's implementation of the interpreter was more complete than mine, I approved of the request as I felt it was a better representative for C++ than what I originally had. Since then, more projects have been added, with some being alternative implementations to an existing language (e.g. `c` and `c-boreddad`, the rust projects, `csharp` and `csharp2`, etc.).

The naming convention for alternatives tend to follow the pattern of either `lang#` or `lang-username`. I propose moving the current `cpp` project to a new directory named `cpp-spongman` (or `cpp2`) so I can continue with my implementation in `cpp` and Spongman can be the code owner for their own implementation.

@Spongman, any questions or objections, please let me know. Thank you.

**Comment by Spongman** [comment]
the diffs would be less if you just added your version add `cpp-...`. i doubt wew're going to rebase master...

**Comment by nicdgonzalez** [comment]
I would prefer if we kept it consistent with the other languages and create a new directory for rewrites. It’s really how we should have done it from the beginning and it’s not too late to do it now.

**Comment by Spongman** [comment]
how's your version coming along, btw? i didn't see a fork with your original code in it.

**Comment by vhladko** [comment]
@Spongman, @nicdgonzalez  I agree with a statement that second created version should go with a prefix. But I also think, that one folder doesn't mean one man works on it and ideally we should have code owner and contributors :) So, if you guys feel that it will be easier for you both go with seaprate folders, then @Spongman I'll ask you to create a folder with prefix for your and make yourself a codeowner, but if you feel that you can complete each other in one perfect folder, then we can keep it as single folder :)

**Comment by Spongman** [comment]
i'm fine with that, it's just that >90% of the git history of the /cpp directory is the code that's currently there. moving that is going to mess with that history.

**Comment by vhladko** [comment]
Hm, maybe I misunderstood something, I thought that @nicdgonzalez wanted to keep cpp in state that it is right now, and you in your second PR with additional changes, gonna copy cpp folder and just rename, and gonna have cpp folder + your changes from second PR and you as codeowner of new repo for future work. Did I misunderstood it ?

**Comment by Spongman** [comment]
> gonna copy cpp folder
that's going to break the history on those files.

**Comment by vhladko** [comment]
so, we gonna have old history in an original cpp folder, and like, one commit for your new folder, I understand but then I don't understand what is your proposal to @nicdgonzalez add his version, do you mean to create a new one from scratch ?

**Comment by Spongman** [comment]
I have updated my omnibus commit with a rename from `cpp` to `cpp-spongman`:
https://github.com/ThePrimeagen/ts-rust-zig-deez/pull/194

**Comment by Spongman** [comment]
there were no files of @nicdgonzalez  left in that folder.

**Comment by Spongman** [comment]
yeah, i did a `git mv cpp cpp-spongman`. if you want the original `cpp` directory back, i suggest retrieving it from the git history. there's nothing in there now that's the same as it was.

**Comment by Spongman** [comment]
also, remember github doesn't show renames correctly. look at the git logs:
```
commit dd1ccecec8c40b591b7c9e0541088506778c802d
Author: Spongman <1088194+Spongman@users.noreply.github.com>
Date:   Tue Jun 6 00:26:32 2023 -0700

    rename cpp->cpp-spongman

diff --git a/cpp/.dockerignore b/cpp-spongman/.dockerignore
similarity index 100%
rename from cpp/.dockerignore
rename to cpp-spongman/.dockerignore
diff --git a/cpp/.editorconfig b/cpp-spongman/.editorconfig
similarity index 100%
rename from cpp/.editorconfig
rename to cpp-spongman/.editorconfig
diff --git a/cpp/.gitignore b/cpp-spongman/.gitignore
similarity index 100%
rename from cpp/.gitignore
rename to cpp-spongman/.gitignore
...
```

**Pull request closed without merging**
