### PR TITLE
Upgraded Kotlin implementation to Multiplatform

### PR DESCRIPTION
**Pull request by ekgame**
This change makes one of the Kotlin implementations multiplatform. That means we can now compile to both Java bytecode (to run on JVM) and JavaScript (to run in node or a browser). 

All tests run in JVM, node.js and a headless browser.

Includes a basic REPL running in a browser. Type-safe CSS goes brrrrr.

### CODE REVIEW

**Comment by vhladko** [comment]
@hermannm could you take a look to this one ? :)

**Comment by hermannm** [comment]
> @hermannm could you take a look to this one ? :)

Will do!

**Review by hermannm — APPROVED** [review]
Great work, looks good! Made a few changes in cc72ec9:
- fixed linter errors and formatting
- flattened folder structure
  - keeping root package in `src` and `test`
  - putting JVM and web in `jvm` and `web`, respectively
- kept `test-ast` and `test-parser` in makefiles, to follow the template from `.github/LANG_TEMPLATE` (although they are kinda useless now)

**Comment by hermannm** [comment]
@vhladko Can you merge? We're renaming `kotlin2` -> `kotlin-multiplatform`, and adding @ekgame and @LizAinslie to the `CODEOWNERS` for it (we're working together, see the thread [here](https://github.com/ThePrimeagen/ts-rust-zig-deez/issues/84#issuecomment-1568660130))

**Comment by vhladko** [comment]
Sure, let’s go :)

**Pull request merged**
