### PR TITLE
Clojure implementation

### PR DESCRIPTION
**Pull request by byrongibby**
Probably a somewhat naive approach that is more or less a straight transcription of the Thorsten Ball book.

### CODE REVIEW

**Comment by vhladko** [comment]
Could you add yourself as a CODEOWNER for this language ?

**Comment by vhladko** [comment]
@byrongibby can you also add Dockerfile or readme how to run this ? :)

**Comment by vhladko** [comment]
and just to mention, we already have one clojure implementation, so you could join that team and help existing repo or keep yours :)

**Comment by byrongibby** [comment]
@vhladko I don't think my implementation really adds anything interesting to what's already been done, I think I'll continue with it on my own for fun and try support the other implementation.

**Comment by vhladko** [comment]
Sounds great, thanks ! :)

**Pull request closed without merging**
