### PR TITLE
Go - Concurrent lexer based on Rob Pike's talk

### PR DESCRIPTION
**Pull request by amis-shokoohi**
I wrote this based on this talk [Lexical Scanning in Go](https://www.youtube.com/watch?v=HxaD_trXwRE) by Rob Pike, where he
implements a concurrent lexer for golang templates.

### CODE REVIEW

**Comment by vhladko** [comment]
Sounds exciting, could you add yourself as Codeowner ?

**Comment by vhladko** [comment]
For some reason, there is a conflict, pls resolve it :)

**Comment by amis-shokoohi** [comment]
Yeah, it's ok now.

**Comment by vhladko** [comment]
Then welcome in a game :)

**Pull request merged**
