### PR TITLE
added prolog implementation

### PR DESCRIPTION
**Pull request by luizcoro2**
I tried my best.

### CODE REVIEW

**Comment by vhladko** [comment]
@luizcoro2 hey, appreciate your effort, we've just merged prolog implementation that was suggested earlier, feel free to help with improvements for already merged version, or if you believe that your implementation can show language from other side - then just rename folder to prolog2 and add yourself to CODEOWNERS, thanks ! :)

**Comment by vhladko** [comment]
Thanks for renaming, pls update Codeowners as well :)

**Comment by luizcoro2** [comment]
Done!

**Comment by vhladko** [comment]
Nice, I think it’s ready to go :)

**Pull request merged**
