### PR TITLE
C#: Changed implementation to use reader instead of position counting…

### PR DESCRIPTION
**Pull request by TomasDurica**
… and added comments for educational purposes

### CODE REVIEW

**Comment by TomasDurica** [comment]
@leo-costa - would it be too bold of me to snag your docker and makefile? Just so I will not have failing checks :)

**Comment by TomasDurica** [comment]
@vhladko - don't want to bother you, but can you take a look when you will have time? :) 
Also, would you prefer to always tag you, or should I just wait :)

**Comment by leo-costa** [comment]
> @leo-costa - would it be too bold of me to snag your docker and makefile? Just so I will not have failing checks :) 

Go ahead! I'm using dotnet 8 tho!

**Comment by TomasDurica** [comment]
@leo-costa - many thanks :) Yes I will make sure it works, I just wanted a start point and I always feel bad when I just blatantly steal stuff :D

**Comment by leo-costa** [comment]
> @leo-costa - many thanks :) Yes I will make sure it works, I just wanted a start point and I always feel bad when I just blatantly steal stuff :D 

I know you mentioned your solution doesn't really care much for speed but for what it is worth, dotnet 8 was about 23% faster than 7.

**Pull request merged**
