### PR TITLE
Kotlin implementation

### PR DESCRIPTION
**Pull request by ekgame**
Apparent there is already #35 and #38 - that's what I get for not checking.
Submitting anyways under "kotlin3", because this implementation is using a bit more idiomatic code and a functional style, closer to the Go implementation in the book.

### CODE REVIEW

**Comment by novusnota** [comment]
Merging in https://github.com/novusnota/monkey-deez

**Comment by vhladko** [comment]
@ekgame Could you add a Dockerfile and Makefile as it is in kotlin2 folder ? It gonna be easier to run and test :)

**Comment by ekgame** [comment]
We formed a group to work on one Kotlin implementation, so I'll help on what is already merged (unless the group falls through). I'll close this for now.

**Comment by vhladko** [comment]
Glad to hear that, good luck ! :)

**Pull request closed without merging**
