### PR TITLE
why did i do this in groovy

### PR DESCRIPTION
**Pull request by trvswgnr**
## hi. me again.

&nbsp;
&nbsp;
all the other languages were taken so i thought "why not learn some Groovy?"
&nbsp;
please merge this i've been working on it for the past 8 hours.
&nbsp;
i have a wife. kids. a family. i know they miss me.
&nbsp;
the lexer has been implemented.
&nbsp;
the test cases pass.
&nbsp;
please.
&nbsp;
&nbsp;
&nbsp;
&nbsp;
you can test it if you want but i promise it works.
&nbsp;
```bash
groovy LexerTest.groovy
```
&nbsp;
i'm going to sleep.

### CODE REVIEW

**Comment by vhladko** [comment]
Hello, thanks for another contribution, we actually have opened PR with groovy but it’s not completed, so I think you can go first :) Can you add yourself as a groovy Codeowner ? :)

**Comment by knudtty** [comment]
lmao exactly what my thoughts were (other groovy open PR guy)

**Comment by trvswgnr** [comment]
> Hello, thanks for another contribution, we actually have opened PR with groovy but it’s not completed, so I think you can go first :) Can you add yourself as a groovy Codeowner ? :)

am i able to add myself? codeowners is new to me, sorry.

**Comment by vhladko** [comment]
> 
Sure, create a new repo name and add yourself to codeowner file :)

**Comment by vhladko** [comment]
Sorry, my bad, just add your nickname and folder name to CODEOWNER file, I’ve missed that it’s your PR, no need to rename anything :)

**Comment by vhladko** [comment]
@trvswgnr can I merge it ? I see you’ve added yourself to codeowners :)

**Comment by trvswgnr** [comment]
> @trvswgnr can I merge it ? I see you’ve added yourself to codeowners :)

ya, i did some more but she's ready to go now

**Comment by vhladko** [comment]
Nice, let’s go :)

**Pull request merged**
