### PR TITLE
Update pr-worthy.yml

### PR DESCRIPTION
**Pull request by Spongman**
use tj-actions/changed-files to calculate which languages require build/test

### CODE REVIEW

**Comment by novusnota** [comment]
@Spongman great addition!

But you probably have to add:

```yaml
uses: actions/checkout@v3
with:
  fetch-depth: 0  # to retrieve all commits
```

```yaml
uses: tj-actions/changed-files@v36
with:
  since-last-remote-commit: true  # to make it work against the most recent additions to master
```

And I'd also suggest adding the `branches:` to the `pull_request:` section on top to make checks run when merging into the master branch and not for everything:

```yaml
pull_request:
  branches: [master]  # only run the workflow on merging into the master branch
```

**Comment by Spongman** [comment]
are you sure `since_last_remote_commit: true` is necessary?
> Defaults to the last non merge commit on the target branch for pull reques events

**Comment by novusnota** [comment]
@Spongman I'm thinking yes, as otherwise it compares the latest state of your PR with the previous commit on your PR, not with the latest remote as a whole. See: [issue and the answer](https://github.com/tj-actions/changed-files/issues/1006)

**Comment by Spongman** [comment]
ok, sounds good. committed.

**Comment by novusnota** [comment]
@vhladko hey, could you please review and/or merge this? :)

**Comment by vhladko** [comment]
Lgtm, merged :)

**Pull request merged**
