### PR TITLE
Common Lisp

### PR DESCRIPTION
**Pull request by lh2**
OK, I haven't actually read the book, but this lexes the example code from the website fine. There is a few things that still need to be made a little nicer, but this is a good start I think.

### CODE REVIEW

**Comment by lh2** [comment]
Progress for today: Expression parsing works now, but there is still some bugs. Prefix operators don't work at all I think.

I think next I will work on the tests, so I can verify what actually works.

**Comment by novusnota** [comment]
Merging in https://github.com/novusnota/monkey-deez

**Comment by ThePrimeagen** [comment]
Looks nice :)

**Comment by ThePrimeagen** [comment]
If you have an added yourself to the code owners, please do that

**Comment by lh2** [comment]
Thanks! Created a new pull request for the code owners thing here: https://github.com/ThePrimeagen/ts-rust-zig-deez/pull/132

**Pull request merged**
