### PR TITLE
Groovy Austin Powers energy (lexer done)

### PR DESCRIPTION
**Pull request by knudtty**
We're getting groovy. Starting chapter 1 today

### CODE REVIEW

**Comment by vhladko** [comment]
Hey, that looks good, but could you mark this PR as a Draft while it’s work in progress ? :)

**Comment by vhladko** [comment]
Hey, there is PR with already finished implementation, we gonna merge it first #148, you can keep your implementation but just change folder name or support existed :)

**Comment by knudtty** [comment]
Sure thing, looks like they're going with interpreted groovy. I'll try compiled groovy!

**Comment by vhladko** [comment]
Sounds great ! :)

**Comment by knudtty** [comment]
Finished Chapter 1

**Comment by vhladko** [comment]
Nice, can I ask you to rename it to something like groovy-compiled or by your nickname, cause groovyc not really clear :) or simple groovy2 also would be nice :)

**Comment by knudtty** [comment]
groovyc is the name of the compiler, is that ok? Otherwise I'll change it as requested

**Comment by vhladko** [comment]
Didn’t know that, the I think it’s fine :)

**Pull request merged**
