### PR TITLE
c++: array concatenation, string indexing, better lexer errors, prelude

### PR DESCRIPTION
**Pull request by Spongman**
- array concatenation
- string indexing
- better lexer errors
- prelude (`TsRustZigDeez -f prelude`)
- `make install`
- `make docker-repl`
- update gtest version
- fix gcc12 warnings
- reduce string allocations in environment get/set
- add fibonacci test (borrowed from lisp versions)
- move builtins & infix operators to global environment
- optimize infix eval
- add '$' unary operator, simplify some prelude functions
- rename cpp->cpp-spongman

### CODE REVIEW

**Comment by vhladko** [comment]
@nicdgonzalez may I ask you review it ? :)

**Comment by Spongman** [comment]
no, i'm not sure how to do that.;

**Comment by vhladko** [comment]
I'm just confused a little bit, that diff shows removing from cpp, Dockerfile, Readme etc

**Comment by vhladko** [comment]
okay, so let me merge this one, and then I'll try to restore the original cpp folder with initial commit.

**Comment by Spongman** [comment]
great, thanks!

**Pull request merged**
