### PR TITLE
[JJDSL] : Feat - Completed Chapter One

### PR DESCRIPTION
**Pull request by Crain-32**
Tom wishes I was his mentor.

Utilizes the Battle Tested Enterprise Standard Java 8. Along with the well documented Nashorn Javascript runtime bundled into the JVM. 

The no-nonsense ECMAScript 5.1 standard allows us to be incredibly clear with our definitions.

Shoutout to @trvswgnr who's Javascript Solution I referenced heavily in the creation of this.

Funnily enough after you get the build system working, it's not... the worst? Still better than CMake.

### CODE REVIEW

**Comment by Crain-32** [comment]
Build will likely continue to fail. By default it pulls from Prime's Master branch, but obviously the defaults don't exist on there yet.

In other words, you have to merge it to know it works in the CI/CD Pipeline, the best type of Situation.

**Comment by vhladko** [comment]
Add yourself as a Codeowner pls :)

**Comment by Crain-32** [comment]
@vhladko do I do that on this branch, or another branch?

**Comment by vhladko** [comment]
You can do this in current PR :)

**Comment by vhladko** [comment]
Nice, merged :)

**Pull request merged**
