### PR TITLE
added a V lang interpreter

### PR DESCRIPTION
**Pull request by FalconEthics**
~ v lang is damn good prime

### CODE REVIEW

**Comment by FalconEthics** [comment]
Common prime, got damn merge it 😑

**Comment by novusnota** [comment]
Merging in https://github.com/novusnota/monkey-deez real soon

**Comment by FalconEthics** [comment]
nice initiative

**Comment by ThePrimeagen** [comment]
ok, merging pr

**Review by ThePrimeagen — APPROVED** [review]

**Pull request merged**
