### PR TITLE
Haskell/state

### PR DESCRIPTION
**Pull request by newmaidumosa**
Haskell implementation of lexer.  Slightly more involved implementation using State Monad and ByteString. More explanation in README.md. 

Passes the 2 tests seen on other implementation.

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
i know nothing about haskell...

could you add yourself to the CODEOWNERS file?

**Comment by newmaidumosa** [comment]
> i know nothing about haskell...
> 
> could you add yourself to the CODEOWNERS file?

I don't know much either. I am not a programmer; this is just sort of a hobby. I find Haskell to be the most interesting language and just thought the Haskell shaped hole in your repo was kind of sad. I am pretty sure I will get overwhelmed very quickly as the project progresses :)

So I don't think that I am fit to have any responsibility on your repo. Adding me to CODEOWNERS maybe not the best idea?

**Comment by ThePrimeagen** [comment]
my guess is you may have to rename this and add yourself as a code owner to your named haskell (my guess is that there is one submitted earlier)

**Comment by newmaidumosa** [comment]
Oh, I didn't realise that there was one submitted already.  What I will do is check if any earlier submission is significantly different to mine and if so I will create another pull request with my named version. 
Thanks for your time.  Will you close this request?

**Pull request merged**
