### PR TITLE
Implement parsing of expressions with yet more big P(H)P energy

### PR DESCRIPTION
**Pull request by wartab**

### CODE REVIEW

**Comment by wartab** [comment]
This is way too fun btw.

**Comment by alberto4673** [comment]
I appreciate the effort you put into this project.

**Comment by alberto4673** [comment]
I think there might be a typo in your README file, just wanted to let you know.

**Review by wartab — COMMENTED** [review]
What do you mean I can't approve my own changes?

**Comment by vhladko** [comment]
@wartab hey, so is it PR ready to be merged ? I see that you are PHP owner, so can merge if it's ready :)

**Comment by ThePrimeagen** [comment]
I merged, welcome to the jungle

**Pull request merged**
