### PR TITLE
C# - Optimization and clean up

### PR DESCRIPTION
**Pull request by Abooow**
This pull request is built upon the foundation set by @redducks100 PR #79. I focused on improving the efficiency of the `Lexer` and improved readability of the code base. I've added an performance test project. The results of the performance tests can be found below:

``` ini

BenchmarkDotNet=v0.13.5, OS=Windows 10 (10.0.19045.2965/22H2/2022Update)
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.400-preview.23225.8
  [Host]     : .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2
  DefaultJob : .NET 7.0.5 (7.0.523.17405), X64 RyuJIT AVX2


```

**redducks100** implementation:
|        Method |      Mean |     Error |    StdDev |       Min |       Max |   Gen0 | Allocated |
|-------------- |----------:|----------:|----------:|----------:|----------:|-------:|----------:|
| SmallCodeTest |  2.157 μs | 0.0227 μs | 0.0212 μs |  2.123 μs |  2.181 μs | 0.1450 |     616 B |
| LargeCodeTest | 55.294 μs | 0.5759 μs | 0.5387 μs | 54.426 μs | 56.098 μs | 3.6621 |   15400 B |

My implementation: *(44.15% faster)*
|        Method |      Mean |     Error |    StdDev |       Min |       Max |   Gen0 | Allocated |
|-------------- |----------:|----------:|----------:|----------:|----------:|-------:|----------:|
| SmallCodeTest |  1.250 μs | 0.0042 μs | 0.0040 μs |  1.243 μs |  1.256 μs | 0.1583 |     664 B |
| LargeCodeTest | 30.897 μs | 0.3221 μs | 0.3013 μs | 30.314 μs | 31.177 μs | 3.9673 |   16600 B |

The small code test includes all token types within 16 lines of code, the large test is the same code repeated 25 times resulting in a total of 448 lines of code.

I tried using a `ReadOnlyMemory<char>` or `Range` instead of `string` for the `Literal` property in `Token`. Of course it resulted in no allocations, but the performance had to suffer instead *(2x slower)*, i'm not sure why this happened, I guess strings are just too optimized.

### CODE REVIEW

**Comment by vhladko** [comment]
Hello, thanks for your effort, the only one problem is that we already have csharp and csharp2 folders, and @redducks100 still need to create a new one as a separate folder, you could wait for him or maybe work together and merge your updated version as csharp 3, also don’t forget to add you as a Codeowner :)

**Comment by redducks100** [comment]
We have decided to push another pr similar to mine @Abooow (check csharp2 implementation), if you want you could add another folder (csharp3) but from what I can see the implementation is really similar to what we already have.

**Comment by vhladko** [comment]
@redducks100 thanks for clarification, so can we then also close your PR ? #79

**Comment by redducks100** [comment]
> @redducks100 thanks for clarification, so can we then also close your PR ? #79

@leo-costa wanted to benchmark my PR and asked not to close it yet, we could move it to draft tho

**Comment by vhladko** [comment]
@redducks100 that would be nice :) I can’t do that to your PR :)

**Comment by Abooow** [comment]
This PR was intended to be what the `csharp2` folder currently is, i guess i was too slow. But it's no problem since they are quite similar anyway.
I don't think we need a `csharp3` folder, having one implementation focused on performance and another on language features should be sufficient. I'm willing to help and contribute in any of the existing implementations. :)

**Comment by vhladko** [comment]
Nice, then I close this one

**Comment by leo-costa** [comment]
Here are some benchmarks that I promised @Abooow @redducks100 @TomasDurica ! Have good weekend 
image

**Comment by TomasDurica** [comment]
Who would've though I am the slowest one :D

**Pull request closed without merging**
