### PR TITLE
Refactored from raw javac to Maven

### PR DESCRIPTION
**Pull request by Crain-32**
Swapped from using `javac` to compile and run, to instead leveraging Maven. Currently fails the Readme Standards in regards to a Makefile/Dockerfile. Hoping someone else makes that change, or I can look into it later.

Decided on the package name `startup.the.monkey`.

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
we have some conflicts

also i need the java owner to step up and review or i'll make you an owner :)

**Comment by Crain-32** [comment]
@ThePrimeagen 
This PR is currently blocked by #108, we want to merge that in, then I'll update the Branch. Was having a conversation with @xNaCly regarding what we want in terms of Build/Structure, and I don't want to override too much work from others.

I was set to be a Code Owner for Java in #100, which appears to be closed. I'll open a separate PR to add myself.

**Comment by RafRunner** [comment]
I'm working on fixing the conflicts and an oversight

**Comment by Crain-32** [comment]
@RafRunner oh perfect. I've been in the office all day, and Prime's discord is distracting me from doing this. Thank you!

**Comment by RafRunner** [comment]
@Crain-32 I created https://github.com/Crain-32/ts-rust-zig-deez/pull/1 😃

If you have any notes, please let me know!

**Comment by vhladko** [comment]
So, #108 is merged, can we move forward with this one ? @Crain-32 @xNaCly  ?

**Comment by xNaCly** [comment]
> So, #108 is merged, can we move forward with this one ? @Crain-32 @xNaCly  ?

Yes, i approved the changes

**Comment by vhladko** [comment]
okay, then let's go :)

**Pull request merged**
