### PR TITLE
Clojure Maintenance PR as CODEOWNER

### PR DESCRIPTION
**Pull request by Vikasg7**
This PR exists only for the purpose for push my change to the ThePrimeagen/ts-rust-zig-deez repository. Everyone else you want to contribute can submit PR to my fork [here](https://github.com/Vikasg7/ts-rust-zig-deez) so that we don't clutter PRs in ThePrimeagen repo.

### CODE REVIEW

**Comment by Vikasg7** [comment]
@vhladko how can I add my change to the repo now as now I have been added to the CodeOwner file?

**Comment by vhladko** [comment]
As your changes target your own repo, don’t you have merge button ? If not, we will discuss it with Prime, cause I’m not aware of codeowners merge strategy :)

**Comment by Vikasg7** [comment]
Sorry, but I am not seeing no approve PR button on my screen.

**Comment by vhladko** [comment]
Approve button should be when you switch to the Files changed tab and there should be green button on the right Review or something like that, and when you click - approve should be there :)

**Comment by Vikasg7** [comment]
Here is what I am seeing. 
image

**Comment by vhladko** [comment]
I see, okay, then looks like you can approve someone else PR to your folder but can’t approve your :) I’ll talk with Prime, but it looks like you just tag one of maintenance when it’s ready and we merge :)

**Comment by vhladko** [comment]
@Vikasg7 do we need to keep this open ? :)

**Comment by Vikasg7** [comment]
@vhladko You can merge it for now. thanks.

**Comment by vhladko** [comment]
Nice, thank you ! :)

**Pull request merged**
