### PR TITLE
[Java] Add to CodeOwners

### PR DESCRIPTION
**Pull request by Crain-32**
As discussed on Stream.

### CODE REVIEW

**Comment by vhladko** [comment]
@xNaCly are you good with that ?

**Comment by xNaCly** [comment]
> @xNaCly are you good with that ?
> 
> 
> 
> @Crain-32 could you also resolve a conflict pls ?
> 
> 


Its not really my decision, its @ThePrimeagen s decision

**Comment by Crain-32** [comment]
@vhladko  Sorry just fixed it.
 You caught me on 1 of 8 days of the year where I spend the entire workday in the office. Should be good now.

**Comment by vhladko** [comment]
Okay, then I’ll merge if it’s something Prime decided :)

**Pull request merged**
