### PR TITLE
Add support for HolyC.

### PR DESCRIPTION
**Pull request by xslendix**

### CODE REVIEW

**Comment by vhladko** [comment]
Looks like there is a conflict in a Codeowner file, can you resolve it so I can merge ? :)

**Comment by xslendix** [comment]
Before you merge, can you please test Dockerfile? I cannot get docker to run so I did it blindly.

**Comment by vhladko** [comment]
Then we have to wait till tomorrow :) my tomorrow, I believe we have different time zone :)

**Comment by xslendix** [comment]
Yeah that's fine lol

**Comment by xslendix** [comment]
I was able to get Docker to run and I have fixed everything there was to fix. I also left a README file explaining more in-depth how all this works. I also created a fork of 3Days to work without audio or SDL2. This is not only faster to build, but also usable in Docker.

**Comment by vhladko** [comment]
Cool ! Then I think we can merge it now :)

**Pull request merged**
