### PR TITLE
Add lexer for deez jdsl

### PR DESCRIPTION
**Pull request by Sergushka**

### CODE REVIEW

**Comment by Crain-32** [comment]
How is this different from the current 2 Kotlin Repos?
image

**Comment by vhladko** [comment]
@Sergushka do you want to keep it as separate version or it’s almost the same as two previous ? I’m not that kotlin developer so can’t judge :)

**Comment by Sergushka** [comment]
I'll continue working on the parser so it will be clearly a different approach even if it's the same language

**Comment by vhladko** [comment]
Okay, then pls add yourself as a Codeowner :)

**Comment by Sergushka** [comment]
I see there is only one kotlin-multiplatform with 3 owners in CODEOWNERS

**Comment by vhladko** [comment]
If you go with your own folder, you need to add your folder name and yourself as a Codeowner of that repo

**Pull request merged**
