### PR TITLE
Dart: Use more language features

### PR DESCRIPTION
**Pull request by shreyassanthu77**
Updated the code to the following dart features:
- Pattern Matching
- Iterators
- Extension methods ( kinda like Traits in rust )

### CODE REVIEW

**Comment by marelle65187512** [comment]
I noticed a bug in your code, here's a possible fix:

**Comment by shreyassanthu77** [comment]
WHAT IS THE BUG!!

**Comment by JikoUnderscore** [comment]
`String c when c.isLetter() => _lookupIdent(
          _readIdentifier(),
        ),
      String c when c.isNumber() => Token(
          TokenType.int,
          _readNumber(),
        ),`

These switch expirations should return early and never call `_readChar();`.
I think this is the bug that @marelle65187512 referred too.

**Comment by shreyassanthu77** [comment]
Yes but I do it a bit differently. I go back after calling read* function so that should not be an issue

**Comment by D-James-GH** [comment]
If using the new dart language features could we not combine token and token type into an enhanced enum (similar to rust's implementation)?

**Comment by shreyassanthu77** [comment]
> If using the new dart language features could we not combine token and token type into an enhanced enum (similar to rust's implementation)? 
Good thought but the problem is dart's enhanced enums aren't like tagged unions ( normal enums in rust ), enhanced enums can have data attached to it's fields ( or whatever you call them IDK ) but they must be constant which means I can't store the name of an identifier or the value of a literal type like string or number that is not known at compile time

**Comment by D-James-GH** [comment]
Ahh yes, of course, I wasn't thinking about dynamic tokens like ident etc...

**Review by Fa-C-Shus — APPROVED** [review]
I like separating the Token code and te addition of utils

**Comment by vhladko** [comment]
@shreyassanthu77 is it ready to be merged ? :)

**Comment by shreyassanthu77** [comment]
Yes 👍

**Comment by Fa-C-Shus** [comment]
> Yes 👍

good job; I'm moving over to Functional Dart with pure functions and immutability

**Comment by vhladko** [comment]
Nice, then let’s go :)

**Comment by shreyassanthu77** [comment]
Hey @vhladko can't I merge my own code into the repo ? I don't want to bother you guys every time I have a new pr.

**Comment by vhladko** [comment]
It’s more question to Prime when he is back :)

**Pull request merged**
