### PR TITLE
Nim

### PR DESCRIPTION
**Pull request by lantos1618**
adding nim, I'm adding it as a direct conv or zig/rust with the same errors as zig/rust

I'm adding nim as is seems like the test won't pass but nor does the rust or zig ver.
¯\_(ツ)_/¯

### CODE REVIEW

**Comment by lantos1618** [comment]
idk if it's expected to fix the issue

**Comment by Echriser** [comment]
I have a Nim implementation at #33

**Comment by lantos1618** [comment]
> I have a Nim implementation at #33

oh yeah you do, didn't see this. 👍 

 if you we end up merging your one. Might want to pick some things out from this commit and update #33. i.e tkKind, token with case kind, unit test, docker file and the local gitignore

**Comment by novusnota** [comment]
Merging in https://github.com/novusnota/monkey-deez

**Comment by vhladko** [comment]
@lantos1618 hey, we've just merged a nim implementation by @Echriser ! :) If you would like to improve some parts of code pls rebase on latest master and do changes to existed version, if you want to have brand new version with your implementation - you could create a nim2 folder and add yourself as nim2 CODEOWNER :)

**Review by vhladko — CHANGES_REQUESTED** [review]
@lantos1618 hey, we've just merged a nim implementation by @Echriser  https://github.com/ThePrimeagen/ts-rust-zig-deez/pull/33 ! :) If you would like to improve some parts of code pls rebase on latest master and do changes to existed version, if you want to have brand new version with your implementation - you could create a nim2 folder and add yourself as nim2 CODEOWNER :)

**Comment by vhladko** [comment]
@lantos1618 I'll close this PR for now, but feel free to re-open or create a new one with requested changes ! :)

**Pull request closed without merging**
