### PR TITLE
More changes to the lexer

### PR DESCRIPTION
**Pull request by Nmerryman**
Cleaned up the code a bit and made it nicer to use/look at.

All of my changes were made while referencing 3 alternative nim implementations (jakelsen, lantos1618, and mine).

We probably need to overhaul the lexer to be much closer to what the book does because there are details that were carefully planed for future use that got discarded. Tests still work of course.

### CODE REVIEW

**Comment by Nmerryman** [comment]
I noticed you said your book hadn't arrived yet, should I be less aggressive with my PRs?

**Comment by vhladko** [comment]
@Echriser could you look on this one ? Btw did you get automatic notification about this PR cause changes are to your owner folder ?

**Comment by Echriser** [comment]
> I noticed you said your book hadn't arrived yet, should I be less aggressive with my PRs?

It's fine. I appreciate the cleanup work. The changes here all look good to me.



> @Echriser could you look on this one ? Btw did you get automatic notification about this PR cause changes are to your owner folder ?

This mention is the only thing that appeared in my email inbox and not the initial PR, so I assume not.

**Comment by vhladko** [comment]
Hm, that’s strange, I would assume that as a Codeowner you should get notification when there are changes to your folder, will work on it :)

**Comment by vhladko** [comment]
@Echriser as it looks good to you, I’ll merge PR :)

**Pull request merged**
