### PR TITLE
Add Nim

### PR DESCRIPTION
**Pull request by Echriser**
deez can

### CODE REVIEW

**Comment by ThePrimeagen** [comment]
please update PR with yourself added to nim codeowners

i need your review for each pr

**Comment by novusnota** [comment]
Merging in https://github.com/novusnota/monkey-deez real soon

**Comment by ThePrimeagen** [comment]
hey @Echriser i don't know what happenend here, but could you rebase off of master and get your changes in?

there is WAY too many files :)

**Comment by Echriser** [comment]
Never touching Github's sync button again.

**Review by vhladko — APPROVED** [review]
looks good ! As it was first nim PR, we gonna merge it first.

**Pull request merged**
